version: '3.7'

services:
  web:
    build:
      context: web/
    volumes:
      - './web:/app'
    ports:
      - 3000:3000

  chain:
    build:
      context: contracts/
    ports:
      - 9615
      - 9944
